<?php
    $shopName = Mage::getStoreConfig('general/store_information/name');
    $tsId = Mage::getStoreConfig('ffuenf_trustedshopsstars/api/tsId');
    $result = Mage::getStoreConfig('ffuenf_trustedshopsstars/data/ratingValue');
    $max = Mage::getStoreConfig('ffuenf_trustedshopsstars/data/bestRating');
    $count = Mage::getStoreConfig('ffuenf_trustedshopsstars/data/ratingCount');
?>
<script type="application/ld+json">
{
    "@context": "http://schema.org/",
    "@type": "LocalBusiness",
    "name": "<?php echo $shopName;?>",
    "description": "<a href=\"https://www.trustedshops.com/buyerrating/info_<?php echo $tsId?>.html\" title=\"<?php echo $shopName;?> custom reviews\" target=\"_blank\"><?php echo $shopName;?> customer reviews | Trusted Shops</a>",
    "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "<?php echo $result;?>",
        "bestRating": "<?php echo $max;?>",
        "ratingCount": "<?php echo $count;?>"
    }
}
</script>